/*
Copyright 2018 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	airflow_v1alpha1 "k8s.io/airflow-operator/pkg/apis/airflow/v1alpha1"
	versioned "k8s.io/airflow-operator/pkg/client/clientset/versioned"
	internalinterfaces "k8s.io/airflow-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "k8s.io/airflow-operator/pkg/client/listers/airflow/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// AirflowBaseInformer provides access to a shared informer and lister for
// AirflowBases.
type AirflowBaseInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AirflowBaseLister
}

type airflowBaseInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAirflowBaseInformer constructs a new informer for AirflowBase type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAirflowBaseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAirflowBaseInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAirflowBaseInformer constructs a new informer for AirflowBase type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAirflowBaseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AirflowV1alpha1().AirflowBases(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AirflowV1alpha1().AirflowBases(namespace).Watch(options)
			},
		},
		&airflow_v1alpha1.AirflowBase{},
		resyncPeriod,
		indexers,
	)
}

func (f *airflowBaseInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAirflowBaseInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *airflowBaseInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&airflow_v1alpha1.AirflowBase{}, f.defaultInformer)
}

func (f *airflowBaseInformer) Lister() v1alpha1.AirflowBaseLister {
	return v1alpha1.NewAirflowBaseLister(f.Informer().GetIndexer())
}
